spring:
  application:
    name: ms-employee-service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: http://localhost:8080/identityiq/scim/v2
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://20.242.136.134:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8081