spring:
  application:
    name: ms-employee-service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: http://135.237.83.37:8080/identityiq/scim/v2
    username: spadmin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: true
#    fetchRegistry: true
#  instance:
#    hostname: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://20.242.136.134:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: ms-employee-service.default.svc.cluster.local

server:
  port: 8081