apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-entitlements
  labels:
    app: ms-entitlements
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-entitlements
  template:
    metadata:
      labels:
        app: ms-entitlements
    spec:
      containers:
        - name: ms-entitlements
          image: dustinyansberg/ms-entitlements:latest
          ports:
            - containerPort: 8081
