apiVersion: v1
kind: Service
metadata:
  name: ms-entitlement-request
spec:
  selector:
    app: ms-entitlements
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
