apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-employee
  labels:
    app: ms-employee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-employee
  template:
    metadata:
      labels:
        app: ms-employee

    spec:
      containers:
        - name: ms-employee

          image: dustinyansberg/ms-employee:latest

          ports:
            - containerPort: 8081
