server:
  port: 9001 # for gabe

# can put routes here
# documentation is here: https://docs.spring.io/spring-cloud-gateway/reference/index.html

spring:
  application:
    name: ms-gateway
  # putting in "test" here instead of actual values for now.
  ## TODO: Update once we have endpoints
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # update to reflect the specific IP addresses - "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
      routes:
        - id: ms-employee-service-route
          uri: lb://ms-employee-service
          predicates:
            - Path=/employee/**
#          filters: # Leaving this here in case it is needed in the future.
#            - SetRequestHeader=Authorization, ${request.headers.Authorization}
        - id: plugin-bridge-route
          uri: lb://plugin-bridge
          predicates:
            - Path=/document/**
        - id: plugin-bridge-appointment-route
          uri: lb://plugin-bridge
          predicates:
            - Path=/appointment/**
        - id: plugin-bridge-notification-route
          uri: lb://plugin-bridge
          predicates:
            - Path=/notification/**
        - id: ms-entitlement-request-route
          uri: lb://ms-entitlement-request
          predicates:
            - Path=/entitlements/**
        - id: ms-accounts-route
          uri: lb://ms-accounts
          predicates:
            - Path=/account/**
        - id: nothing-route
          uri: lb://nothing
          predicates:
            - Path=/nothing/**
          
#          filters:
#          - name: CircuitBreaker
#            args:
#              name: employeeFallbackController
#              fallbackUri: forward:/fallback/employee
        

# This section is for what will display one our health checks
# localhost:9001/actuator is the endpoint
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - beans
  endpoint:
    health:
      group:
        system:
          show-details: always

# health.show-details allows us to hit the /actuator/health endpoint and get info, otherwise it just shows "UP"
# since "UP" is likely all Eureka needs, we'll just keep it untouched for now, but we can implement it if needed
#      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      productFallbackController:
        wait-duration-in-open-state: 15000

# for eureka connection
eureka:
  client:
    service-url:
      defaultZone: http://20.242.136.134:8761/eureka # Default value for eureka
  instance:
    hostname: 4.156.40.62
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka # Default value for eureka
#  instance:
#    hostname: localhost
