server:
  error:
    whitelabel:
      enabled: false
  port: 9001 # for gabe

# can put routes here
# documentation is here: https://docs.spring.io/spring-cloud-gateway/reference/index.html

spring:
  main:
    web-application-type: reactive
# TODO do we need this mvc thing?
#  mvc:
#    throw-exception-if-no-handler-found: true
  application:
    name: ms-gateway
  web:
    resources:
      add-mappings: false
  # putting in "test" here instead of actual values for now.
  ## TODO: Update once we have endpoints
  cloud:
    gateway:
      routes:
        - id: ms-employee-service-route
          uri: lb://ms-employee-service
          predicates:
            - Path=/employee/**
#          filters:
#          - name: CircuitBreaker
#            args:
#              name: employeeFallbackController
#              fallbackUri: forward:/fallback/employee

# This section is for what will display one our health checks
# localhost:9001/actuator is the endpoint
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - beans
  endpoint:
    health:
      group:
        system:
          show-details: always

# health.show-details allows us to hit the /actuator/health endpoint and get info, otherwise it just shows "UP"
# since "UP" is likely all Eureka needs, we'll just keep it untouched for now, but we can implement it if needed
#      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      productFallbackController:
        wait-duration-in-open-state: 15000

# for eureka connection
eureka:
  client:
    service-url:
      defaultZone: http://20.242.136.134:8761/eureka # Default value for eureka
  instance:
    hostname: 4.156.40.62
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka # Default value for eureka
#  instance:
#    hostname: localhost

okta:
  oauth2:
    issuer: https://dev-gdc5jpwq2csxld4e.us.auth0.com/
    audience: https://shs-api-gateway.com
    
application:
  client-origin-url: http://localhost:4200


  
