
server:
  port: 9001    # for gabe

# can put routes here
# documentation is here: https://docs.spring.io/spring-cloud-gateway/reference/index.html

 
spring:
  application:
    name: ms-gateway
# putting in "test" here instead of actual values for now
  cloud:
    gateway:
      routes:
        - id: ms-test-route
          uri: lb://ms-test-route
          predicates:
          - Path=/test-endpoint/**
          filters:
          - name: CircuitBreaker
            args:
              name: testFallbackController
              fallbackUri: forward:/fallback/test



management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - beans
  endpoint:
    health:
      group:
        system:
          show-details: always

resilience4j:
  circuitbreaker:
    instances:
      productFallbackController:
        wait-duration-in-open-state: 15000
        

# for eureka connection
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Default value for eureka