apiVersion: v1

kind: Service
metadata:
  name: customconnectorapp
spec:
  selector:
    app: customconnectorapp
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  type: LoadBalancer
