#spring.application.name=CustomConnectorApp
#server.port=9003
#
#spring.datasource.url=jdbc:mysql://localhost:3306/custom_connector_app
#
##	Change these to the username and password of the remote database.
#spring.datasource.username=root
#spring.datasource.password=jeg4oOEQHNs-0grth
#
#spring.jpa.hibernate.ddl-auto=none
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#spring.security.user.name=username
#spring.security.user.password=pasword


spring:
  application:
    name: CustomConnectorApp
  datasource:
    url: jdbc:mysql://localhost:3306/jmai_connector_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      generate-ddl: false
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9003
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://20.242.136.134:8761/eureka/
#    registerWithEureka: true
#    fetchRegistry: true
#  instance:
#    hostname: ms-accounts.default.svc.cluster.local
  
  
